export const routes = {
  HOME: '/',
  ABOUT: '/about',
  GALLERY: '/gallery',
  CONTACTS: '/contacts',
  NEWS: '/news',
  LITERATURE: '/literature',
  RUSSIAN: '/russian',
  CONTESTS: '/contests',
  ACHIEVEMENTS: '/achievements',
  COURSES: '/courses',
  FIFTH_GRADE: '/fifth-grade',
  SIXTH_GRADE: '/sixth-grade',
  SEVENTH_GRADE: '/seventh-grade',
  EIGHTH_GRADE: '/eighth-grade',
  NINTH_GRADE: '/ninth-grade',
};
